global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: go_api
    metrics_path: /metrics
    static_configs:
      - targets: ["go_api:3001"]

  - job_name: go_api_ready
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://go_api:3001/health/ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: go_api_live
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://go_api:3001/health/live
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
